#https://hub.docker.com/r/linuxserver/freshrss
services:
  freshrss:
    image: linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /freshrss_config:/config
    ports:
      - 8020:80
    restart: unless-stopped
