#Audiobookshelf
# https://www.audiobookshelf.org/docs/#docker-compose-install
# https://hub.docker.com/r/advplyr/audiobookshelf


services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    ports:
      - 8011:80
    volumes:
      - /media/sf_audiobooks:/audiobooks
#      - </path/to/audiobooks>:/audiobooks
#      - </path/to/podcasts>:/podcasts
      - /home/hostadmin/Syncthing/docker/audiobookshelf_config:/config
      - /home/hostadmin/Syncthing/docker/audiobookshelf_metadata:/metadata
    environment:
      - TZ=America/New_York
